dist: bionic
sudo: false
language: cpp

env:
  global:
    - UNICORN_VERSION=1.0.1
  matrix:
    - LUA_VERSION=5.1
    - LUA_VERSION=5.2
    - LUA_VERSION=5.3
    - LUA_VERSION=luajit2.0

os:
  - linux
  - osx
  - windows

python:
  - "3.7"

# Needed for CMake 3.12+
osx_image: xcode10

addons:
  apt:
    packages:
      - python3-pip
      - python-dev

matrix:
  allow_failures:
    # LuaJIT is super finicky on OSX when using doctest so we're not gonna care too much
    # about it failing. If it works on all the other platforms, it'll probably work for
    # LuaJIT + OSX too.
    - os: osx
      env: LUA_VERSION=luajit2.0

before_install:
  - bash ci/travis-setup.sh
  # Debugging stuff. The `|| true` is necessary for Windows, which only has an executable
  # named `python`. Whether you get Python 2 or 3 depends on $PATH.
  - python -V
  - python2 -V || true
  - python3 -V || true
  - cmake --version

install: bash ci/travis-install.sh

script: bash ci/travis-run.sh
