dist: bionic
sudo: true
language: cpp

env:
  global:
    - UNICORN_VERSION=1.0.1
  matrix:
    - LUA_VERSION=5.1
    - LUA_VERSION=5.2
    - LUA_VERSION=5.3
    - LUA_VERSION=5.4
    - LUA_VERSION=luajit2.0

os:
  - linux
  - osx

python:
  - "3.7"

# Needed for CMake 3.12+
osx_image: xcode10

addons:
  apt:
    packages:
      - python3-pip
      - python-dev

matrix:
  allow_failures:
    # LuaJIT is super finicky on OSX when using doctest so we're not gonna care too much
    # about it failing. If it works on all the other platforms, it'll probably work for
    # LuaJIT + OSX too.
    - os: osx
      env: LUA_VERSION=luajit2.0

before_install:
  - pip3 install -U pip setuptools
  # Debugging
  - pip3 --version
  - python3 -V
  - cmake --version

install:
  - git clone --depth 1 https://github.com/unicorn-engine/unicorn.git unicorn-${UNICORN_VERSION}
  - pushd unicorn-${UNICORN_VERSION}
  - git fetch --all --tags --prune
  - git checkout ${UNICORN_VERSION}
  - ./make.sh
  - sudo ./make.sh install
  - popd

script: |
  ./tools/lua_venv.py -l --config-out ~/settings.json $LUA_VERSION ~/__lua${LUA_VERSION}
  ./configure --venv-config ~/settings.json
  mkdir build                               && \
  cd build                                  && \
  cmake -DCMAKE_VERBOSE_MAKEFILE=YES ..     && \
  make                                      && \
  ctest --output-on-failure
