dist: bionic
sudo: true
language: cpp

env:
  global:
    - UNICORN_VERSION=1.0.1
  matrix:
    - LUA_VERSION=5.1
    - LUA_VERSION=5.2
    - LUA_VERSION=5.3
    - LUA_VERSION=5.4
    - LUA_VERSION=luajit2.0

os:
  - linux
  - osx

python:
  - "3.7"

# Needed for CMake 3.12+
osx_image: xcode10

addons:
  apt:
    packages:
      - python3-pip
      - python-dev

matrix:
  allow_failures:
    # LuaJIT is super finicky on OSX when using doctest so we're not gonna care too much
    # about it failing. If it works on all the other platforms, it'll probably work for
    # LuaJIT + OSX too.
    - os: osx
      env: LUA_VERSION=luajit2.0

before_install:
  - pip3 install -U pip setuptools
  # Debugging
  - pip3 --version
  - python3 -V
  - cmake --version

install:
  - ./tools/ci/install-unicorn.sh ${UNICORN_VERSION}
  - ./tools/ci/build-project.sh ${LUA_VERSION}

script:
  ctest --output-on-failure
