language: c

env:
  global:
    - LUAROCKS_VERSION=3.0.3
    - UNICORN_VERSION=1.0.1
  matrix:
    - LUA_TEST_VERSION=5.1.5
    - LUA_TEST_VERSION=5.2.4
    - LUA_TEST_VERSION=5.3.5

branches:
  only:
    - master
