language: c

env:
  global:
    - LUAROCKS=3.0.3
    - UNICORN_VERSION_TAG=1.0.1
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit
    - LUA=luajit2.0
    - LUA=luajit2.1

branches:
  only:
    - master

before_install:
  - source .travis/setenv_lua.sh
  - sudo apt-get install luarocks
  - sudo luarocks install busted

  # Get Unicorn on our machine. It's not in a Debian package so we have to build
  # it from the source.
  - bash .travis/set_up_unicorn.sh

