dist: bionic
sudo: false
language: cpp

env:
  global:
    - UNICORN_VERSION=1.0.1
  matrix:
    - LUA_VERSION=5.1
    - LUA_VERSION=5.2
    - LUA_VERSION=5.3
    - LUA_VERSION=luajit2.0

os:
  - linux
  - osx
  - windows

matrix:
  allow_failures:
    - os: windows

before_install:
  - bash ./travis-setup.sh

install:
  - git clone --depth 1 https://github.com/unicorn-engine/unicorn.git unicorn-${UNICORN_VERSION}
  - pushd unicorn-${UNICORN_VERSION}
  - git fetch --all --tags --prune
  - git checkout ${UNICORN_VERSION}
  - ./make.sh
  - sudo ./make.sh install
  - popd
  - curl -L http://git.io/lenv | perl
