dist: bionic
sudo: true
language: cpp

env:
  global:
    - UNICORN_VERSION=1.0.1
  matrix:
    - LUA_VERSION=5.1
    - LUA_VERSION=5.2
    - LUA_VERSION=5.3
    - LUA_VERSION=luajit2.0

os:
  - linux
  - osx

# Needed for CMake 3.12+
osx_image: xcode10

addons:
  apt:
    packages:
      - cmake
    sources:
      - kalakris-cmake
    update: true

matrix:
  allow_failures:
    # LuaJIT is super finicky on OSX when using doctest so we're not gonna care too much
    # about it failing. If it works on all the other platforms, it'll probably work for
    # LuaJIT + OSX too.
    - os: osx
      env: LUA_VERSION=luajit2.0

before_install:
  # NOTE: This will break the builds when Travis changes the version(s) of Python they
  # have installed.
  - |
    if [[ $TRAVIS_OS_NAME = 'linux' ]]; then
      pyenv local 2.7.15 3.7.1
    fi
  # Debugging
  - python2 -V
  - python3 -V
  - cmake --version
  - which cmake

install:
  - pip3 install -U -r python-requirements.txt
  - git clone --depth 1 https://github.com/unicorn-engine/unicorn.git unicorn-${UNICORN_VERSION}
  - pushd unicorn-${UNICORN_VERSION}
  - git fetch --all --tags --prune
  - git checkout ${UNICORN_VERSION}
  - ./make.sh
  - sudo ./make.sh install
  - popd

script: |
  ./configure --venv-version $LUA_VERSION   && \
  mkdir build                               && \
  cd build                                  && \
  cmake -DCMAKE_VERBOSE_MAKEFILE=YES ..     && \
  make                                      && \
  ctest --output-on-failure
