#!/bin/sh

export LUA_CPATH="@CMAKE_CURRENT_BINARY_DIR@/?@CMAKE_SHARED_LIBRARY_SUFFIX@;@CMAKE_CURRENT_BINARY_DIR@/?/init@CMAKE_SHARED_LIBRARY_SUFFIX@;@LUA_CUSTOM_CPATH@;$LUA_CPATH"
export LUA_PATH="@CMAKE_CURRENT_BINARY_DIR@/?.lua;@CMAKE_CURRENT_BINARY_DIR@/?/init.lua;@LUA_CUSTOM_LPATH@;$LUA_PATH"

@BUSTED_EXE@ @BUSTED_CLI_ARGS@ -f @CMAKE_CURRENT_BINARY_DIR@/.busted
