# WARNING: This makefile is intended to be invoked by LuaRocks, not manually. Only use
# it form `clean`, `format` and if your IDE is grumpy, `autogen-files` might work.

# If we don't disable suffixes, Make fails to detect our default %.o rule because it has
# extra prerequisites. Because of this, it falls back to its internal built-in recipe for
# %.o from %.c. This default rule doesn't have any of the header search paths, and will
# fail.
.SUFFIXES:

.DELETE_ON_ERROR:

################################################################################
# DEFAULTS
# These are only used when this Makefile is run manually. You should only be
# doing that for `make clean`. Use `luarocks` for everything else.

CP = cp
LIB_EXTENSION = so
LUAROCKS = luarocks
OBJ_EXTENSION = o
UNICORN_INCDIR = /usr/include

LUA := $(shell $(LUAROCKS) config variables.LUA)
LUA_DIR := $(shell $(LUAROCKS) config variables.LUA_DIR)
LUA_INCDIR = $(LUA_DIR)/include
LUA_VERSION = $(shell $(LUA) -e 'print(_VERSION:sub(5))')

################################################################################

# Because Unicorn can be customized to exclude architectures, not all of these may be
# supported by the C library. Missing architectures are automatically detected and excluded
# at build time.
ARCHITECTURES = arm64 arm m68k mips ppc riscv s390x sparc tricore x86

SOURCE_DIR = csrc
LUA_SOURCE_DIR = src/unicorn
AUTOGENERATED_LUA_FILES = $(foreach s,registers unicorn $(ARCHITECTURES),$(LUA_SOURCE_DIR)/$(s)_const.lua)
LDOC_FILES = $(foreach s,unicorn $(ARCHITECTURES),$(LUA_SOURCE_DIR)/$(s)_const.luadoc)

C_TEMPLATE_SOURCES = $(wildcard $(SOURCE_DIR)/*.template)
AUTOGENERATED_C_FILES = $(C_TEMPLATE_SOURCES:.template=.c)

HEADER_TEMPLATE_SOURCES = $(wildcard $(SOURCE_DIR)/unicornlua/*.template)
AUTOGENERATED_H_FILES = $(HEADER_TEMPLATE_SOURCES:.template=.h)

ALL_AUTOGENERATED_SOURCES = $(AUTOGENERATED_C_FILES) $(AUTOGENERATED_H_FILES) $(AUTOGENERATED_LUA_FILES)

LIB_BUILD_TARGET = $(SOURCE_DIR)/unicorn_c_.$(LIB_EXTENSION)
LIB_C_SOURCES = \
    $(addprefix $(SOURCE_DIR)/,control_functions.c engine.c hooks.c registers_api.c unicorn.c) \
    $(AUTOGENERATED_C_FILES)
LIB_OBJECT_FILES = $(LIB_C_SOURCES:.c=.$(OBJ_EXTENSION))

TEMPLATE_DATA_FILES = $(wildcard $(SOURCE_DIR)/template_data/*.lua)

LIBRARY_DIRECTORIES = $(strip $(UNICORN_LIBDIR) $(PTHREAD_LIBDIR))

# The hardcoded version-specific paths here are fallbacks because my IDE can't find the
# Lua headers without them. Is it necessary? No. Will it cause problems? Unlikely. But
# without it, every file is a sea of red squiggles and I'm. Losing. My. Mind.
HEADER_DIRECTORIES = $(strip \
	$(SOURCE_DIR) \
    $(LUA_INCDIR) \
    $(UNICORN_INCDIR) \
    /usr/local/include \
    /usr/include/lua$(LUA_VERSION) \
    /usr/local/include/lua$(LUA_VERSION))

INCLUDE_PATH_FLAGS = $(addprefix -I,$(HEADER_DIRECTORIES))
LIB_PATH_FLAGS = $(addprefix -L,$(LIBRARY_DIRECTORIES))
REQUIRED_LIBS = unicorn pthread
REQUIRED_LIBS_FLAGS = $(addprefix -l,$(REQUIRED_LIBS))

C_CMD = $(CC) $(INCLUDE_PATH_FLAGS) $(CFLAGS) $(USER_CFLAGS)
LINK_CMD = $(LD) $(LIB_PATH_FLAGS) $(LDFLAGS)


# Uncomment for debugging autogenerated files
#.PRECIOUS: $(ALL_AUTOGENERATED_SOURCES) \
#           $(LUA_SOURCE_DIR)/%_const_gen.c \
#           $(LUA_SOURCE_DIR)/%_extracted_consts.txt \
#           $(LUA_SOURCE_DIR)/%_extracted_consts.lua \
#           %registers_const_gen.c \
#           %_const_gen.c


# This must be the first rule, don't move it.
$(LIB_BUILD_TARGET): $(LIB_OBJECT_FILES) $(AUTOGENERATED_LUA_FILES)
	$(LINK_CMD) $(LIBFLAG) -o $@ $(filter-out %.lua,$^) $(REQUIRED_LIBS_FLAGS)


%.$(OBJ_EXTENSION): %.c $(AUTOGENERATED_H_FILES)
	$(C_CMD) -c -o $@ $<


%.c: %.template $(TEMPLATE_DATA_FILES)
	$(LUA) tools/render_template.lua -o $@ $^


%.h: %.template $(TEMPLATE_DATA_FILES)
	$(LUA) tools/render_template.lua -o $@ $^


$(LUA_SOURCE_DIR)/%_extracted_consts.txt:
	$(LUA) tools/process_header.lua --missing-ok $(UNICORN_INCDIR)/unicorn/$*.h $@


%registers_const_gen.c: templates/registers_const_generator.template \
                        $(SOURCE_DIR)/template_data/register_types.lua \
                        $(SOURCE_DIR)/template_data/predefined_docstrings.lua \
                        $(SOURCE_DIR)/unicornlua/register_types.h
	$(LUA) tools/render_template.lua -o $@ $(filter-out %.h,$^)


%_const_gen.c: templates/arch_const_generator.template  %_extracted_consts.txt
	$(LUA) tools/render_template.lua -o $@ $^


%_const_gen: %_const_gen.c
	$(CC) $(INCLUDE_PATH_FLAGS) -o $@ $<


%_const.lua: %_const_gen
	$< > $@


%_const.luadoc: templates/arch_const_ldoc.template \
                %_extracted_consts.txt \
                $(SOURCE_DIR)/template_data/predefined_docstrings.lua
	$(LUA) tools/render_template.lua -o $@ $^


.PHONY: __install
__install: $(LIB_BUILD_TARGET) $(AUTOGENERATED_LUA_FILES)
	$(CP) $(LIB_BUILD_TARGET) $(INST_LIBDIR)
	$(CP) -r $(LUA_SOURCE_DIR) $(INST_LUADIR)


.PHONY: all
all: $(LIB_BUILD_TARGET) $(AUTOGENERATED_LUA_FILES)


.PHONY: clean
clean:
	$(RM) $(LIB_OBJECT_FILES) $(LIB_BUILD_TARGET) $(ALL_AUTOGENERATED_SOURCES) $(LDOC_FILES)


.PHONY: format
format:
	@clang-format --Werror -i --verbose \
	    $(filter-out $(AUTOGENERATED_C_FILES),$(wildcard $(SOURCE_DIR)/*.c)) \
	    $(filter-out $(AUTOGENERATED_H_FILES),$(wildcard $(SOURCE_DIR)/unicornlua/*.h))


.PHONY: docs
docs: $(ALL_AUTOGENERATED_SOURCES) $(LDOC_FILES) $(LUA_SOURCE_DIR)/registers_const.lua
	ldoc .


# Convenience target for generating all templated files. This is mostly for
# making IDEs and linters shut up about "missing" files.
.PHONY: autogen-files
autogen-files: $(ALL_AUTOGENERATED_SOURCES)
