-- These are docstrings defined for constants exported from Unicorn headers.
docstrings = {
    unicorn = {
        UC_ARCH_ARM = "Specifies the ARM architecture, used in @{unicorn.open}.",
        UC_ARCH_ARM64 = "Specifies the ARM64 architecture, used in @{unicorn.open}.",
        UC_ARCH_M68K = "Specifies the Motorola 68000 architecture, used in @{unicorn.open}.",
        UC_ARCH_MAX = "Internal to Unicorn. Do not use.",
        UC_ARCH_MIPS = "Specifies the MIPS architecture, used in @{unicorn.open}.",
        UC_ARCH_PPC = "Specifies the PowerPC architecture, used in @{unicorn.open}.",
        UC_ARCH_RISCV = "Specifies the RISC-V architecture, used in @{unicorn.open}.",
        UC_ARCH_S390X = "Specifies the s390x architecture, used in @{unicorn.open}.",
        UC_ARCH_SPARC = "Specifies the SPARC architecture, used in @{unicorn.open}.",
        UC_ARCH_TRICORE = "Specifies the Tricore architecture, used in @{unicorn.open}.",
        UC_ARCH_X86 = "Specifies the x86 architecture, used in @{unicorn.open}.",
        UC_ERR_ARCH = "Invalid/unsupported architecture",
        UC_ERR_ARG = "Invalid argument",
        UC_ERR_EXCEPTION = "Unhandled CPU exception",
        UC_ERR_FETCH_PROT = "Fetch from non-executable memory",
        UC_ERR_FETCH_UNALIGNED = "Fetch from unaligned memory",
        UC_ERR_FETCH_UNMAPPED = "Invalid memory fetch",
        UC_ERR_HANDLE = "Invalid handle",
        UC_ERR_HOOK = "Invalid hook type",
        UC_ERR_HOOK_EXIST = "Unknown",
        UC_ERR_INSN_INVALID = "Invalid instruction",
        UC_ERR_MAP = "Invalid memory mapping",
        UC_ERR_MODE = "Invalid mode",
        UC_ERR_NOMEM = "No memory available or memory not present",
        UC_ERR_OK = "OK",
        UC_ERR_READ_PROT = "Read from non-readable memory",
        UC_ERR_READ_UNALIGNED = "Read from unaligned memory",
        UC_ERR_READ_UNMAPPED = "Invalid memory read",
        UC_ERR_RESOURCE = "Insufficient resource",
        UC_ERR_VERSION = "Different API version between core & binding",
        UC_ERR_WRITE_PROT = "Write to write-protected memory",
        UC_ERR_WRITE_UNALIGNED = "Write to unaligned memory",
        UC_ERR_WRITE_UNMAPPED = "Invalid memory write",
    },
}
