describe('Test submodule require()', function ()
    describe('arm', function() require 'unicorn.arm' end)
    describe('arm64', function () require 'unicorn.arm64' end)
    describe('m68k', function () require 'unicorn.m68k' end)
    describe('mips', function () require 'unicorn.mips' end)
    describe('sparc', function () require 'unicorn.sparc' end)
    describe('x86', function () require 'unicorn.x86' end)
end)
