/**
 * File autogenerated by CMake @CMAKE_VERSION@
 * Generating compiler: @CMAKE_C_COMPILER_ID@ @CMAKE_C_COMPILER_VERSION@
 *
 * DO NOT MODIFY.
 *
 * @file platform.h
 */


#ifndef UNICORNLUA_PLATFORM_H
#define UNICORNLUA_PLATFORM_H

#cmakedefine01 CMAKE_HOST_APPLE
#cmakedefine01 CMAKE_HOST_UNIX

#endif  /* UNICORNLUA_PLATFORM_H */
