name: CI

on: [ push ]

jobs:
  testing:
    runs-on: ${{ matrix.operating-system }}
    env:
      # We need the MACOSX_DEPLOYMENT_TARGET environment variable because of
      # a linker error that happens with LuaJIT:
      # https://github.com/LuaJIT/LuaJIT/issues/449
      MACOSX_DEPLOYMENT_TARGET: "11"
      # We get a linker error if we don't mess with the library path. For some
      # reason, /usr/lib64 isn't on the default search path.
      LD_LIBRARY_PATH: /usr/lib64:${LD_LIBRARY_PATH}
      CTEST_FULL_OUTPUT: "1"
    strategy:
      fail-fast: false
      matrix:
        operating-system:
          - ubuntu-latest
          - macos-latest
          # - windows-latest
        lua-version:
          - "5.1"
          - "5.2"
          - "5.3"
          - "5.4"
          - "luajit-2.0.5"
    steps:
      - uses: actions/checkout@v3
      # - name: Windows Prep
      #   uses: ilammy/msvc-dev-cmd@v1
      #   if: ${{ contains(matrix.operating-system, 'windows') }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Lua
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: ${{ matrix.lua-version }}
      - name: Install LuaRocks
        # Note: This is a fork of the original by leafo. Switch back to that once
        # https://github.com/leafo/gh-actions-luarocks/pull/14 has been merged.
        uses: hishamhm/gh-actions-luarocks@5013277f6f115c27478f18c1f647f8de98390628
      - name: Install Unicorn
        run: make -C tools/ci install_unicorn UNICORN_VERSION=1.0.2
      - name: Environment
        run: luarocks config
      - name: Install Binding
        run: luarocks build
      - name: Run tests
        run: luarocks test
