name: CI

on: [ push ]

jobs:
  testing:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system:
          - ubuntu-latest
          - macos-latest
        lua-version:
          - "5.1"
          - "5.2"
          - "5.3"
          - "5.4"
          # We can't specifically select versions of LuaJIT as of August 2024. This may or
          # may not be fixable.
          # https://github.com/leafo/gh-actions-lua/issues/49
          - "luajit-openresty"  # Judging from the docs, this is basically LuaJIT 2.1
        unicorn-version:
          - "1.0.3"
          - "2.0.1.post1"
          - "2.1.0"
        exclude:
          # Unicorn 1.x breaks on macOS 14+
          - operating-system: macos-latest
            unicorn-version: "1.0.3"
        include:
          - operating-system: macos-13
            unicorn-version: "1.0.3"
            lua-version: "5.1"
          - operating-system: macos-13
            unicorn-version: "1.0.3"
            lua-version: "5.2"
          - operating-system: macos-13
            unicorn-version: "1.0.3"
            lua-version: "5.3"
          - operating-system: macos-13
            unicorn-version: "1.0.3"
            lua-version: "5.4"
          - operating-system: macos-13
            unicorn-version: "1.0.3"
            lua-version: "luajit-openresty"
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          persist-credentials: false
      - name: Install Lua
        uses: leafo/gh-actions-lua@v11
        with:
          luaVersion: ${{ matrix.lua-version }}
          # We need LUAJIT_ENABLE_GC64 on MacOS: https://github.com/moonjit/moonjit/issues/121
          luaCompileFlags: XCFLAGS="-DLUAJIT_ENABLE_GC64=1"
      - name: Install LuaRocks
        uses: leafo/gh-actions-luarocks@v5
        with:
          luaRocksVersion: "3.11.1"
      - name: Cache Unicorn
        id: cache-built-unicorn
        uses: actions/cache@v4
        with:
          path: |
            /usr/include/unicorn
            /usr/local/include/unicorn
            /usr/lib64/libunicorn.*
            /usr/local/lib/libunicorn.*
          key: unicorn-cached-${{ runner.os }}-${{ matrix.unicorn-version }}
      - if: ${{ steps.cache-built-unicorn.outputs.cache-hit != 'true' }}
        name: Install Unicorn
        run: make -C tools/ci install_unicorn UNICORN_VERSION=${{ matrix.unicorn-version }}
      - name: Environment
        run: luarocks config
      - name: Install Binding
        run: luarocks build
        env:
          # We need to disable the newline-eof warning because third-party code trips the
          # warning. We could use `-isystem` instead of `-I` for adding include paths to
          # third-party headers, but that's specific to GCC and Clang.
          USER_CFLAGS: -Wall -Wextra -Werror -Wpedantic -pedantic-errors -Wno-newline-eof
      - name: Run tests
        run: luarocks test
        env:
          LD_LIBRARY_PATH: /usr/lib64:/usr/local/lib:${LD_LIBRARY_PATH}
          DYLD_FALLBACK_LIBRARY_PATH: /usr/lib64:/usr/local/lib:${DYLD_FALLBACK_LIBRARY_PATH}
#
#  testing-windows:
#    runs-on: windows-2022
#    strategy:
#      fail-fast: false
#      matrix:
#        lua-version:
#          - "5.1"
#          - "5.2"
#          - "5.3"
#          - "5.4"
#          - "luajit-openresty"
#        unicorn-version:
#          - "1.0.3"
#          - "2.0.1.post1"
#          - "2.1.0"
#    steps:
#      - uses: actions/checkout@v4.1.7
#        with:
#          persist-credentials: false
#      - name: Install Lua
#        uses: leafo/gh-actions-lua@v11
#        with:
#          luaVersion: ${{ matrix.lua-version }}
#      - name: Install LuaRocks
#        # Note: This is a fork of the original by leafo. Switch back to that once
#        # https://github.com/leafo/gh-actions-luarocks/pull/14 has been merged.
#        uses: hishamhm/gh-actions-luarocks@8acd6db166a0162c375fa8647a0350fbec46940e
#        with:
#          luaRocksVersion: "3.11.1"
#      - name: Install Unicorn
#        run: make -C tools/ci install_unicorn UNICORN_VERSION=${{ matrix.unicorn-version }}
#      - name: Environment
#        run: luarocks config
#      - name: Install Binding
#        run: luarocks build
#      - name: Run tests
#        run: luarocks test
