name: CI

on: [ push ]

jobs:
  testing-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - lua-version: "5.1"
          - lua-version: "5.2"
          - lua-version: "5.3"
          - lua-version: "5.4"
          - lua-version: "luajit2.0"
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install Unicorn
        run: ./tools/ci/install-unicorn.sh 1.0.2
      - name: Set up Lua
        run: |
          python3 ./tools/lua_venv.py -l -o settings.json ${{ matrix.lua-version }} __lua${{ matrix.lua-version }}
      - name: Configure build
        run: python3 ./configure --venv-config settings.json
      - name: Build
        run: |
          cmake -B build -S . -DCMAKE_VERBOSE_MAKEFILE=YES
          make
      - name: Run tests
        # We get a linker error if we don't mess with the library path. For some
        # reason, /usr/lib64 isn't on the default search path.
        run: |
          export LD_LIBRARY_PATH=/usr/lib64:${LD_LIBRARY_PATH}
          ctest --output-on-failure
        working-directory: build

  # TODO (dargueta): Test on OSX
  # TODO (dargueta): Test on Windows?
