name: CI

on: [ push ]

jobs:
  testing:
    runs-on: ${{ matrix.operating-system }}
    env:
      # We need the MACOSX_DEPLOYMENT_TARGET environment variable because of
      # a linker error that happens with LuaJIT:
      # https://github.com/LuaJIT/LuaJIT/issues/449
      MACOSX_DEPLOYMENT_TARGET: 10.14
      # We get a linker error if we don't mess with the library path. For some
      # reason, /usr/lib64 isn't on the default search path.
      LD_LIBRARY_PATH: /usr/lib64:${LD_LIBRARY_PATH}
    strategy:
      fail-fast: false
      matrix:
        operating-system:
          - ubuntu-20.04
          - macos-10.15
        lua-version:
          - "5.1"
          - "5.2"
          - "5.3"
          - "5.4"
          - "luajit2.0"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Unicorn
        run: ./tools/ci/install-unicorn.sh 1.0.2
      - name: Set up Lua
        run: python3 ./tools/lua_venv.py -l -o settings.json ${{ matrix.lua-version }} .venv
      # The `install` command will trigger an automatic build configuration. For
      # our purposes we don't need to run the `configure` script.
      - name: Install
        run: sudo make install
      - name: Run tests
        run: make test

  # TODO (dargueta): Test on Windows?
